package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "user_name"))
public class Administrateur implements java.io.Serializable {

	private Integer idAd;
	private Date dateInscpAdm;
	private Date dateNaissenceAdm;
	private String email;
	private String nomAdm;
	private String numTele;
	private String password;
	private String prenomAdm;
	private String userName;

	public Administrateur() {
	}

	public Administrateur(Date dateInscpAdm, String email, String nomAdm, String password, String prenomAdm,
			String userName) {
		this.dateInscpAdm = dateInscpAdm;
		this.email = email;
		this.nomAdm = nomAdm;
		this.password = password;
		this.prenomAdm = prenomAdm;
		this.userName = userName;
	}

	public Administrateur(Date dateInscpAdm, Date dateNaissenceAdm, String email, String nomAdm, String numTele,
			String password, String prenomAdm, String userName) {
		this.dateInscpAdm = dateInscpAdm;
		this.dateNaissenceAdm = dateNaissenceAdm;
		this.email = email;
		this.nomAdm = nomAdm;
		this.numTele = numTele;
		this.password = password;
		this.prenomAdm = prenomAdm;
		this.userName = userName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ad", unique = true, nullable = false)
	public Integer getIdAd() {
		return this.idAd;
	}

	public void setIdAd(Integer idAd) {
		this.idAd = idAd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_inscp_adm", nullable = false, length = 10)
	public Date getDateInscpAdm() {
		return this.dateInscpAdm;
	}

	public void setDateInscpAdm(Date dateInscpAdm) {
		this.dateInscpAdm = dateInscpAdm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissence_adm", length = 10)
	public Date getDateNaissenceAdm() {
		return this.dateNaissenceAdm;
	}

	public void setDateNaissenceAdm(Date dateNaissenceAdm) {
		this.dateNaissenceAdm = dateNaissenceAdm;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nom_adm", nullable = false, length = 45)
	public String getNomAdm() {
		return this.nomAdm;
	}

	public void setNomAdm(String nomAdm) {
		this.nomAdm = nomAdm;
	}

	@Column(name = "num_tele")
	public String getNumTele() {
		return this.numTele;
	}

	public void setNumTele(String numTele) {
		this.numTele = numTele;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "prenom_adm", nullable = false, length = 45)
	public String getPrenomAdm() {
		return this.prenomAdm;
	}

	public void setPrenomAdm(String prenomAdm) {
		this.prenomAdm = prenomAdm;
	}

	@Column(name = "user_name", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
