package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chapitre generated by hbm2java
 */
@Entity
@Table(name = "chapitre", catalog = "pfe")
public class Chapitre implements java.io.Serializable {

	private Integer idChpt;
	private Modul modul;
	private String contenue;
	private Date dateAjoute;
	private String titre;

	public Chapitre() {
	}

	public Chapitre(Modul modul, String titre) {
		this.modul = modul;
		this.titre = titre;
	}

	public Chapitre(Modul modul, String contenue, Date dateAjoute, String titre) {
		this.modul = modul;
		this.contenue = contenue;
		this.dateAjoute = dateAjoute;
		this.titre = titre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chpt", unique = true, nullable = false)
	public Integer getIdChpt() {
		return this.idChpt;
	}

	public void setIdChpt(Integer idChpt) {
		this.idChpt = idChpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModul() {
		return this.modul;
	}

	public void setModul(Modul modul) {
		this.modul = modul;
	}

	@Column(name = "contenue", length = 2250)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ajoute", length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

	@Column(name = "titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

}
