package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "user_name"))
public class Enseignant implements java.io.Serializable {

	private Integer idEng;
	private Date dateInscpEng;
	private Date dateNaissanceEng;
	private String email;
	private String nomEng;
	private String numTele;
	private String password;
	private String prenomEng;
	private String userName;
	private Set<Modul> moduls = new HashSet<Modul>(0);

	public Enseignant() {
	}

	public Enseignant(Date dateInscpEng, String email, String nomEng, String password, String prenomEng,
			String userName) {
		this.dateInscpEng = dateInscpEng;
		this.email = email;
		this.nomEng = nomEng;
		this.password = password;
		this.prenomEng = prenomEng;
		this.userName = userName;
	}

	public Enseignant(Date dateInscpEng, Date dateNaissanceEng, String email, String nomEng, String numTele,
			String password, String prenomEng, String userName, Set<Modul> moduls) {
		this.dateInscpEng = dateInscpEng;
		this.dateNaissanceEng = dateNaissanceEng;
		this.email = email;
		this.nomEng = nomEng;
		this.numTele = numTele;
		this.password = password;
		this.prenomEng = prenomEng;
		this.userName = userName;
		this.moduls = moduls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_eng", unique = true, nullable = false)
	public Integer getIdEng() {
		return this.idEng;
	}

	public void setIdEng(Integer idEng) {
		this.idEng = idEng;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_inscp_eng", nullable = false, length = 10)
	public Date getDateInscpEng() {
		return this.dateInscpEng;
	}

	public void setDateInscpEng(Date dateInscpEng) {
		this.dateInscpEng = dateInscpEng;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance_eng", length = 10)
	public Date getDateNaissanceEng() {
		return this.dateNaissanceEng;
	}

	public void setDateNaissanceEng(Date dateNaissanceEng) {
		this.dateNaissanceEng = dateNaissanceEng;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nom_eng", nullable = false, length = 45)
	public String getNomEng() {
		return this.nomEng;
	}

	public void setNomEng(String nomEng) {
		this.nomEng = nomEng;
	}

	@Column(name = "num_tele")
	public String getNumTele() {
		return this.numTele;
	}

	public void setNumTele(String numTele) {
		this.numTele = numTele;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "prenom_eng", nullable = false, length = 45)
	public String getPrenomEng() {
		return this.prenomEng;
	}

	public void setPrenomEng(String prenomEng) {
		this.prenomEng = prenomEng;
	}

	@Column(name = "user_name", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enseignant")
	public Set<Modul> getModuls() {
		return this.moduls;
	}

	public void setModuls(Set<Modul> moduls) {
		this.moduls = moduls;
	}

}
