package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exercice generated by hbm2java
 */
@Entity
@Table(name = "exercice", catalog = "pfe")
public class Exercice implements java.io.Serializable {

	private Integer idEx;
	private Modul modul;
	private String contenue;
	private Date dateAjoute;
	private String nomEx;

	public Exercice() {
	}

	public Exercice(Modul modul, String contenue, String nomEx) {
		this.modul = modul;
		this.contenue = contenue;
		this.nomEx = nomEx;
	}

	public Exercice(Modul modul, String contenue, Date dateAjoute, String nomEx) {
		this.modul = modul;
		this.contenue = contenue;
		this.dateAjoute = dateAjoute;
		this.nomEx = nomEx;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ex", unique = true, nullable = false)
	public Integer getIdEx() {
		return this.idEx;
	}

	public void setIdEx(Integer idEx) {
		this.idEx = idEx;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModul() {
		return this.modul;
	}

	public void setModul(Modul modul) {
		this.modul = modul;
	}

	@Column(name = "contenue", nullable = false, length = 2250)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ajoute", length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

	@Column(name = "nom_ex", nullable = false, length = 45)
	public String getNomEx() {
		return this.nomEx;
	}

	public void setNomEx(String nomEx) {
		this.nomEx = nomEx;
	}

}
