package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "pfe")
public class Filiere implements java.io.Serializable {

	private Integer idFil;
	private Departement departement;
	private String codeFil;
	private String nomFil;
	private Set<Modul> moduls = new HashSet<Modul>(0);

	public Filiere() {
	}

	public Filiere(Departement departement, String codeFil, String nomFil) {
		this.departement = departement;
		this.codeFil = codeFil;
		this.nomFil = nomFil;
	}

	public Filiere(Departement departement, String codeFil, String nomFil, Set<Modul> moduls) {
		this.departement = departement;
		this.codeFil = codeFil;
		this.nomFil = nomFil;
		this.moduls = moduls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_fil", unique = true, nullable = false)
	public Integer getIdFil() {
		return this.idFil;
	}

	public void setIdFil(Integer idFil) {
		this.idFil = idFil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "code_fil", nullable = false, length = 45)
	public String getCodeFil() {
		return this.codeFil;
	}

	public void setCodeFil(String codeFil) {
		this.codeFil = codeFil;
	}

	@Column(name = "nom_fil", nullable = false, length = 45)
	public String getNomFil() {
		return this.nomFil;
	}

	public void setNomFil(String nomFil) {
		this.nomFil = nomFil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Modul> getModuls() {
		return this.moduls;
	}

	public void setModuls(Set<Modul> moduls) {
		this.moduls = moduls;
	}

}
