package testaa;
// Generated 9 juin 2023, 00:46:10 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "immobilier")
public class Images implements java.io.Serializable {

	private Integer idImage;
	private String chemin;
	private int maison;

	public Images() {
	}

	public Images(String chemin, int maison) {
		this.chemin = chemin;
		this.maison = maison;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_image", unique = true, nullable = false)
	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	@Column(name = "chemin", nullable = false)
	public String getChemin() {
		return this.chemin;
	}

	public void setChemin(String chemin) {
		this.chemin = chemin;
	}

	@Column(name = "maison", nullable = false)
	public int getMaison() {
		return this.maison;
	}

	public void setMaison(int maison) {
		this.maison = maison;
	}

}
