package testaa;
// Generated 9 juin 2023, 00:46:10 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Maison generated by hbm2java
 */
@Entity
@Table(name = "maison", catalog = "immobilier")
public class Maison implements java.io.Serializable {

	private Integer idMaison;
	private String titre;
	private String description;
	private int nbChambre;
	private Integer prixVender;
	private Integer prixLouerMoins;
	private Integer prixLouerJour;
	private int categorie;
	private int proprietaire;

	public Maison() {
	}

	public Maison(String titre, String description, int nbChambre, int categorie, int proprietaire) {
		this.titre = titre;
		this.description = description;
		this.nbChambre = nbChambre;
		this.categorie = categorie;
		this.proprietaire = proprietaire;
	}

	public Maison(String titre, String description, int nbChambre, Integer prixVender, Integer prixLouerMoins,
			Integer prixLouerJour, int categorie, int proprietaire) {
		this.titre = titre;
		this.description = description;
		this.nbChambre = nbChambre;
		this.prixVender = prixVender;
		this.prixLouerMoins = prixLouerMoins;
		this.prixLouerJour = prixLouerJour;
		this.categorie = categorie;
		this.proprietaire = proprietaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_maison", unique = true, nullable = false)
	public Integer getIdMaison() {
		return this.idMaison;
	}

	public void setIdMaison(Integer idMaison) {
		this.idMaison = idMaison;
	}

	@Column(name = "titre", nullable = false)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "nb_chambre", nullable = false)
	public int getNbChambre() {
		return this.nbChambre;
	}

	public void setNbChambre(int nbChambre) {
		this.nbChambre = nbChambre;
	}

	@Column(name = "prix_vender")
	public Integer getPrixVender() {
		return this.prixVender;
	}

	public void setPrixVender(Integer prixVender) {
		this.prixVender = prixVender;
	}

	@Column(name = "prix_louer_moins")
	public Integer getPrixLouerMoins() {
		return this.prixLouerMoins;
	}

	public void setPrixLouerMoins(Integer prixLouerMoins) {
		this.prixLouerMoins = prixLouerMoins;
	}

	@Column(name = "prix_louer_jour")
	public Integer getPrixLouerJour() {
		return this.prixLouerJour;
	}

	public void setPrixLouerJour(Integer prixLouerJour) {
		this.prixLouerJour = prixLouerJour;
	}

	@Column(name = "categorie", nullable = false)
	public int getCategorie() {
		return this.categorie;
	}

	public void setCategorie(int categorie) {
		this.categorie = categorie;
	}

	@Column(name = "proprietaire", nullable = false)
	public int getProprietaire() {
		return this.proprietaire;
	}

	public void setProprietaire(int proprietaire) {
		this.proprietaire = proprietaire;
	}

}
