package testaa;
// Generated 9 juin 2023, 00:46:10 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaisonCategorie generated by hbm2java
 */
@Entity
@Table(name = "maison_categorie", catalog = "immobilier")
public class MaisonCategorie implements java.io.Serializable {

	private Integer id;
	private int maison;
	private int categorie;

	public MaisonCategorie() {
	}

	public MaisonCategorie(int maison, int categorie) {
		this.maison = maison;
		this.categorie = categorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "maison", nullable = false)
	public int getMaison() {
		return this.maison;
	}

	public void setMaison(int maison) {
		this.maison = maison;
	}

	@Column(name = "categorie", nullable = false)
	public int getCategorie() {
		return this.categorie;
	}

	public void setCategorie(int categorie) {
		this.categorie = categorie;
	}

}
