package testaa;
// Generated 9 juin 2023, 00:46:10 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MaisonConsommateur generated by hbm2java
 */
@Entity
@Table(name = "maison_consommateur", catalog = "immobilier")
public class MaisonConsommateur implements java.io.Serializable {

	private Integer id;
	private int consommateur;
	private int maison;
	private Date dateDebut;
	private Date dateSortie;

	public MaisonConsommateur() {
	}

	public MaisonConsommateur(int consommateur, int maison, Date dateDebut, Date dateSortie) {
		this.consommateur = consommateur;
		this.maison = maison;
		this.dateDebut = dateDebut;
		this.dateSortie = dateSortie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "consommateur", nullable = false)
	public int getConsommateur() {
		return this.consommateur;
	}

	public void setConsommateur(int consommateur) {
		this.consommateur = consommateur;
	}

	@Column(name = "maison", nullable = false)
	public int getMaison() {
		return this.maison;
	}

	public void setMaison(int maison) {
		this.maison = maison;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_sortie", nullable = false, length = 10)
	public Date getDateSortie() {
		return this.dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

}
