package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "pfe")
public class Message implements java.io.Serializable {

	private Integer idMsg;
	private String contenue;
	private Date dateEnvoi;
	private int receiver;
	private int sender;

	public Message() {
	}

	public Message(String contenue, Date dateEnvoi, int receiver, int sender) {
		this.contenue = contenue;
		this.dateEnvoi = dateEnvoi;
		this.receiver = receiver;
		this.sender = sender;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_msg", unique = true, nullable = false)
	public Integer getIdMsg() {
		return this.idMsg;
	}

	public void setIdMsg(Integer idMsg) {
		this.idMsg = idMsg;
	}

	@Column(name = "contenue", nullable = false)
	public String getContenue() {
		return this.contenue;
	}

	public void setContenue(String contenue) {
		this.contenue = contenue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_envoi", nullable = false, length = 10)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@Column(name = "receiver", nullable = false)
	public int getReceiver() {
		return this.receiver;
	}

	public void setReceiver(int receiver) {
		this.receiver = receiver;
	}

	@Column(name = "sender", nullable = false)
	public int getSender() {
		return this.sender;
	}

	public void setSender(int sender) {
		this.sender = sender;
	}

}
