package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NoteQuiz generated by hbm2java
 */
@Entity
@Table(name = "note_quiz", catalog = "pfe")
public class NoteQuiz implements java.io.Serializable {

	private Integer idNote;
	private Etudiante etudiante;
	private Quiz quiz;
	private int noteQuiz;

	public NoteQuiz() {
	}

	public NoteQuiz(Etudiante etudiante, Quiz quiz, int noteQuiz) {
		this.etudiante = etudiante;
		this.quiz = quiz;
		this.noteQuiz = noteQuiz;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_note", unique = true, nullable = false)
	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etu", nullable = false)
	public Etudiante getEtudiante() {
		return this.etudiante;
	}

	public void setEtudiante(Etudiante etudiante) {
		this.etudiante = etudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_quiz", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "note_quiz", nullable = false)
	public int getNoteQuiz() {
		return this.noteQuiz;
	}

	public void setNoteQuiz(int noteQuiz) {
		this.noteQuiz = noteQuiz;
	}

}
