package testaa;
// Generated 15 juin 2023, 19:03:38 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name = "quiz", catalog = "pfe")
public class Quiz implements java.io.Serializable {

	private Integer idQz;
	private Modul modul;
	private Date dateAjoute;
	private Date dateLimite;
	private String titre;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<NoteQuiz> noteQuizs = new HashSet<NoteQuiz>(0);

	public Quiz() {
	}

	public Quiz(Modul modul, Date dateAjoute, String titre) {
		this.modul = modul;
		this.dateAjoute = dateAjoute;
		this.titre = titre;
	}

	public Quiz(Modul modul, Date dateAjoute, Date dateLimite, String titre, Set<Question> questions,
			Set<NoteQuiz> noteQuizs) {
		this.modul = modul;
		this.dateAjoute = dateAjoute;
		this.dateLimite = dateLimite;
		this.titre = titre;
		this.questions = questions;
		this.noteQuizs = noteQuizs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_qz", unique = true, nullable = false)
	public Integer getIdQz() {
		return this.idQz;
	}

	public void setIdQz(Integer idQz) {
		this.idQz = idQz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModul() {
		return this.modul;
	}

	public void setModul(Modul modul) {
		this.modul = modul;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ajoute", nullable = false, length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_limite", length = 10)
	public Date getDateLimite() {
		return this.dateLimite;
	}

	public void setDateLimite(Date dateLimite) {
		this.dateLimite = dateLimite;
	}

	@Column(name = "titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<NoteQuiz> getNoteQuizs() {
		return this.noteQuizs;
	}

	public void setNoteQuizs(Set<NoteQuiz> noteQuizs) {
		this.noteQuizs = noteQuizs;
	}

}
